# Generated by Django 4.2.19 on 2025-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="events/")),
                ("description", models.TextField()),
                ("link", models.URLField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("webinar", "Webinar"),
                            ("conference", "Conference"),
                            ("workshop", "Workshop"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_host", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("date_time", models.DateTimeField()),
            ],
        ),
    ]
