# Generated by Django 4.2.19 on 2025-02-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("system_admin", "System Admin"),
                    ("administrator", "Administrator"),
                    ("contributor", "Contributor"),
                    ("user", "Normal User"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
