# Generated by Django 4.2.19 on 2025-02-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_manager", "0002_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("1", "Male"), ("2", "Female")],
                max_length=1,
                null=True,
            ),
        ),
    ]
