# Generated by Django 4.2.19 on 2025-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("host_phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("linkedin_profile", models.URLField()),
                ("description", models.TextField()),
                ("host_name", models.CharField(max_length=255)),
                ("evaluation_details", models.TextField()),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[("paid", "Paid"), ("knowledge", "Knowledge")],
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("close_date", models.DateField()),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("finance", "Finance"),
                            ("agriculture", "Agriculture"),
                            ("healthcare", "Healthcare"),
                            ("security", "Security"),
                            ("education", "Education"),
                            ("business", "Business"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("poster_image", models.ImageField(upload_to="challenge_posters/")),
                ("prize", models.CharField(max_length=50)),
            ],
        ),
    ]
